package site.addzero.dioxus.buddy.preview

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.nio.file.Files
import kotlin.io.path.createDirectories
import kotlin.io.path.readText

class DioxusPreviewSandboxTest {
    @Test
    fun `extract expands workspace dependencies and rebases Cargo path dependencies`() {
        val workspaceRoot = Files.createTempDirectory("dioxus-buddy-workspace")
        val pluginRoot = workspaceRoot.resolve("apps/az-aio/plugins/algorithm-center").createDirectories()
        val sandboxRoot = pluginRoot.resolve(".dioxus-buddy/preview-sandbox/algorithmtile")
        val workspaceManifest = workspaceRoot.resolve("apps/az-aio/plugins/Cargo.toml")
        workspaceManifest.parent.createDirectories()
        Files.write(
            workspaceManifest,
            """
            [workspace]

            [workspace.dependencies]
            anyhow = "1.0.99"
            az-algorithm = { version = "=2026.5.10", path = "../../../crates/algorithm/az-algorithm" }
            az-dioxus-components = { version = "=2026.5.10", path = "../../../crates/ui/az-dioxus-components" }
            dioxus = { version = "0.7.9", default-features = false, features = ["html", "macro", "signals"] }
            """.trimIndent().toByteArray(Charsets.UTF_8),
        )
        val manifest = """
            [package]
            name = "algorithm-center"
            edition.workspace = true

            [dependencies]
            anyhow.workspace = true
            az-aio-platform = { path = "../../platform" }
            az-algorithm.workspace = true
            az-dioxus-components.workspace = true
            dioxus.workspace = true
            """.trimIndent()

        val result = CargoDependencySectionExtractor.extract(
            manifestText = manifest,
            manifestRootPath = pluginRoot,
            sandboxRootPath = sandboxRoot,
        )

        assertEquals(
            listOf(
                "anyhow = \"1.0.99\"",
                "az-aio-platform = { path = \"../../../../../platform\" }",
                "az-algorithm = { version = \"=2026.5.10\", path = \"../../../../../../../crates/algorithm/az-algorithm\" }",
                "az-dioxus-components = { version = \"=2026.5.10\", path = \"../../../../../../../crates/ui/az-dioxus-components\" }",
            ),
            result.dependencies,
        )
    }

    @Test
    fun `generated root gitignore ignores all sandbox files`() {
        val generatedRoot = Files.createTempDirectory("dioxus-buddy-generated")

        DioxusBuddyGeneratedFiles.writeGitignore(generatedRoot)

        assertEquals(
            "# Generated by Dioxus Buddy.\n*\n",
            generatedRoot.resolve(".gitignore").readText(),
        )
    }

    @Test
    fun `package edition resolves from explicit workspace`() {
        val workspaceRoot = Files.createTempDirectory("dioxus-buddy-workspace")
        val pluginRoot = workspaceRoot.resolve("plugins/algorithm-center").createDirectories()
        Files.write(
            workspaceRoot.resolve("Cargo.toml"),
            """
            [workspace]

            [workspace.package]
            edition = "2024"
            """.trimIndent().toByteArray(Charsets.UTF_8),
        )
        val manifest = """
            [package]
            name = "algorithm-center"
            edition.workspace = true
            workspace = "../.."
            """.trimIndent()

        assertEquals(
            "2024",
            CargoPackageMetadata.resolveEdition(
                manifestText = manifest,
                manifestRootPath = pluginRoot,
                fallback = "2021",
            ),
        )
    }

    @Test
    fun `path rewrite keeps absolute paths when relative path cannot be computed`() {
        val workspaceRoot = Files.createTempDirectory("dioxus-buddy-workspace")
        val pluginRoot = workspaceRoot.resolve("plugin").createDirectories()
        val sandboxRoot = pluginRoot.resolve(".dioxus-buddy/preview-sandbox/card")
        val absoluteDependency = workspaceRoot.resolve("shared/crate").createDirectories().toAbsolutePath()
        val manifest = """
            [dependencies]
            shared = { path = "$absoluteDependency" }
            """.trimIndent()

        val result = CargoDependencySectionExtractor.extract(
            manifestText = manifest,
            manifestRootPath = pluginRoot,
            sandboxRootPath = sandboxRoot,
        )

        assertTrue(result.dependencies.single().contains("""path = "../../../../shared/crate""""))
    }
}
