package site.addzero.dioxus.buddy.preview

import site.addzero.dioxus.buddy.model.DioxusPreviewParser
import site.addzero.dioxus.buddy.model.DioxusPreviewTarget
import java.nio.file.Files
import java.nio.file.Path
import java.util.Comparator
import kotlin.io.path.createDirectories
import kotlin.io.path.exists

data class DioxusPreviewSandbox(
    val rootPath: Path,
    val cargoTomlPath: Path,
    val mainFilePath: Path,
    val sourceFilePath: Path,
    val url: String,
)

object DioxusPreviewSandboxWriter {
    private const val DIOXUS_VERSION = "0.7"

    fun write(target: DioxusPreviewTarget): DioxusPreviewSandbox {
        val rootPath = target.cargoManifest.rootPath
            .resolve(".dioxus-buddy")
            .resolve("preview-sandbox")
            .resolve(target.functionName.toSlug())

        replaceDirectory(rootPath)
        val sourceDirectory = rootPath.resolve("src").createDirectories()
        val sourceFilePath = sourceDirectory.resolve("preview_source.rs")
        val mainFilePath = sourceDirectory.resolve("main.rs")
        val cargoTomlPath = rootPath.resolve("Cargo.toml")

        writeUtf8(sourceFilePath, target.sourceText.prepareIncludedSource())
        writeUtf8(mainFilePath, renderMainFile(target))
        writeUtf8(cargoTomlPath, renderCargoToml(target))

        return DioxusPreviewSandbox(
            rootPath = rootPath,
            cargoTomlPath = cargoTomlPath,
            mainFilePath = mainFilePath,
            sourceFilePath = sourceFilePath,
            url = "http://localhost:${target.previewPort}",
        )
    }

    private fun renderMainFile(target: DioxusPreviewTarget): String {
        return buildString {
            appendLine("// Generated by Dioxus Buddy.")
            appendLine("// Original file: ${target.sourceFile.path}")
            appendLine("#![allow(dead_code, unused_imports, unused_variables, non_snake_case)]")
            appendLine()
            appendLine("include!(\"preview_source.rs\");")
            appendLine()
            appendLine("fn DioxusBuddyPreviewRoot() -> dioxus::prelude::Element {")
            appendLine("    ${target.functionName}()")
            appendLine("}")
            appendLine()
            appendLine("fn main() {")
            appendLine("    dioxus::launch(DioxusBuddyPreviewRoot);")
            appendLine("}")
        }
    }

    private fun renderCargoToml(target: DioxusPreviewTarget): String {
        val originalManifest = runCatching {
            String(Files.readAllBytes(target.cargoManifest.manifestPath), Charsets.UTF_8)
        }.getOrDefault("")
        val dependencyText = CargoDependencySectionExtractor.extract(originalManifest)

        return buildString {
            appendLine("[workspace]")
            appendLine()
            appendLine("[package]")
            appendLine("name = \"dioxus-buddy-preview-${target.functionName.toSlug()}\"")
            appendLine("version = \"0.1.0\"")
            appendLine("edition = \"${target.cargoManifest.edition}\"")
            appendLine("publish = false")
            appendLine()
            appendLine("[dependencies]")
            appendLine("dioxus = { version = \"$DIOXUS_VERSION\", features = [\"web\"] }")
            dependencyText.dependencies.forEach(::appendLine)
            dependencyText.extraTables.forEach { table ->
                appendLine()
                appendLine(table)
            }
        }
    }

    private fun String.prepareIncludedSource(): String {
        return renameStandaloneMainFunctions()
    }

    private fun String.renameStandaloneMainFunctions(): String {
        val parsedFunctions = DioxusPreviewParser.parse(this)
        val previewRanges = parsedFunctions.map { it.functionOffset until it.functionEndOffset }
        val mainRegex = Regex("""\bfn\s+main\s*\(""")
        return mainRegex.replace(this) { match ->
            val insidePreview = previewRanges.any { range -> match.range.first in range }
            if (insidePreview) {
                match.value
            } else {
                match.value.replace("main", "__dioxus_buddy_original_main")
            }
        }
    }

    private fun replaceDirectory(path: Path) {
        if (!path.exists()) {
            path.createDirectories()
            return
        }
        Files.walk(path)
            .sorted(Comparator.reverseOrder())
            .forEach(Files::delete)
        path.createDirectories()
    }

    private fun writeUtf8(
        path: Path,
        text: String,
    ) {
        Files.write(path, text.toByteArray(Charsets.UTF_8))
    }

    private fun String.toSlug(): String {
        return lowercase()
            .replace(Regex("""[^a-z0-9_-]+"""), "-")
            .trim('-')
            .ifBlank { "preview" }
    }
}

private object CargoDependencySectionExtractor {
    private val dependencyTableRegex = Regex(
        """^\s*\[(target\.[^\]]+\.dependencies|dependencies(?:\.[^\]]+)?)\]\s*$""",
    )

    fun extract(manifestText: String): CargoDependencyText {
        val lines = manifestText.lines()
        val dependencies = mutableListOf<String>()
        val extraTables = mutableListOf<String>()
        var index = 0

        while (index < lines.size) {
            val line = lines[index]
            val tableName = dependencyTableRegex.find(line)?.groupValues?.getOrNull(1)
            if (tableName == null) {
                index++
                continue
            }

            val body = mutableListOf<String>()
            index++
            while (index < lines.size && !lines[index].trimStart().startsWith("[")) {
                body += lines[index]
                index++
            }

            if (tableName == "dependencies") {
                dependencies += body.filterDependencyLines()
            } else if (!tableName.endsWith(".dioxus")) {
                val filtered = body.filterDependencyLines()
                if (filtered.isNotEmpty()) {
                    extraTables += buildString {
                        appendLine("[$tableName]")
                        filtered.forEach(::appendLine)
                    }.trimEnd()
                }
            }
        }

        return CargoDependencyText(
            dependencies = dependencies.distinct(),
            extraTables = extraTables.distinct(),
        )
    }

    private fun List<String>.filterDependencyLines(): List<String> {
        return filter { line ->
            val trimmed = line.trim()
            when {
                trimmed.isBlank() -> false
                trimmed.startsWith("#") -> false
                trimmed.startsWith("dioxus ") -> false
                trimmed.startsWith("dioxus=") -> false
                trimmed.startsWith("dioxus_") -> true
                Regex("""^dioxus\s*=""").containsMatchIn(trimmed) -> false
                trimmed.contains("workspace = true") -> false
                else -> true
            }
        }
    }
}

private data class CargoDependencyText(
    val dependencies: List<String>,
    val extraTables: List<String>,
)
