package site.addzero.dioxus.buddy.preview

import site.addzero.dioxus.buddy.model.DioxusPreviewParser
import site.addzero.dioxus.buddy.model.DioxusPreviewTarget
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import java.util.Comparator
import kotlin.io.path.createDirectories
import kotlin.io.path.exists

data class DioxusPreviewSandbox(
    val rootPath: Path,
    val cargoTomlPath: Path,
    val mainFilePath: Path,
    val sourceFilePath: Path,
    val url: String,
)

object DioxusPreviewSandboxWriter {
    private const val DIOXUS_VERSION = "0.7"

    fun write(target: DioxusPreviewTarget): DioxusPreviewSandbox {
        val generatedRootPath = target.cargoManifest.rootPath.resolve(".dioxus-buddy")
        val rootPath = generatedRootPath
            .resolve("preview-sandbox")
            .resolve(target.functionName.toSlug())

        DioxusBuddyGeneratedFiles.writeGitignore(generatedRootPath)
        replaceDirectory(rootPath)
        val sourceDirectory = rootPath.resolve("src").createDirectories()
        val sourceFilePath = sourceDirectory.resolve("preview_source.rs")
        val mainFilePath = sourceDirectory.resolve("main.rs")
        val cargoTomlPath = rootPath.resolve("Cargo.toml")

        writeUtf8(sourceFilePath, target.sourceText.prepareIncludedSource())
        writeUtf8(mainFilePath, renderMainFile(target))
        writeUtf8(cargoTomlPath, renderCargoToml(target))

        return DioxusPreviewSandbox(
            rootPath = rootPath,
            cargoTomlPath = cargoTomlPath,
            mainFilePath = mainFilePath,
            sourceFilePath = sourceFilePath,
            url = "http://localhost:${target.previewPort}",
        )
    }

    private fun renderMainFile(target: DioxusPreviewTarget): String {
        return buildString {
            appendLine("// Generated by Dioxus Buddy.")
            appendLine("// Original file: ${target.sourceFile.path}")
            appendLine("#![allow(dead_code, unused_imports, unused_variables, non_snake_case)]")
            appendLine()
            appendLine("include!(\"preview_source.rs\");")
            appendLine()
            appendLine("fn DioxusBuddyPreviewRoot() -> dioxus::prelude::Element {")
            appendLine("    ${target.functionName}()")
            appendLine("}")
            appendLine()
            appendLine("fn main() {")
            appendLine("    dioxus::launch(DioxusBuddyPreviewRoot);")
            appendLine("}")
        }
    }

    private fun renderCargoToml(target: DioxusPreviewTarget): String {
        val originalManifest = runCatching {
            String(Files.readAllBytes(target.cargoManifest.manifestPath), Charsets.UTF_8)
        }.getOrDefault("")
        val rootPath = target.cargoManifest.rootPath
            .resolve(".dioxus-buddy")
            .resolve("preview-sandbox")
            .resolve(target.functionName.toSlug())
        val dependencyText = CargoDependencySectionExtractor.extract(
            manifestText = originalManifest,
            manifestRootPath = target.cargoManifest.rootPath,
            sandboxRootPath = rootPath,
        )
        val edition = CargoPackageMetadata.resolveEdition(
            manifestText = originalManifest,
            manifestRootPath = target.cargoManifest.rootPath,
            fallback = target.cargoManifest.edition,
        )

        return buildString {
            appendLine("[workspace]")
            appendLine()
            appendLine("[package]")
            appendLine("name = \"dioxus-buddy-preview-${target.functionName.toSlug()}\"")
            appendLine("version = \"0.1.0\"")
            appendLine("edition = \"$edition\"")
            appendLine("publish = false")
            appendLine()
            appendLine("[dependencies]")
            appendLine("dioxus = { version = \"$DIOXUS_VERSION\", features = [\"web\"] }")
            dependencyText.dependencies.forEach(::appendLine)
            dependencyText.extraTables.forEach { table ->
                appendLine()
                appendLine(table)
            }
        }
    }

    private fun String.prepareIncludedSource(): String {
        return renameStandaloneMainFunctions()
    }

    private fun String.renameStandaloneMainFunctions(): String {
        val parsedFunctions = DioxusPreviewParser.parse(this)
        val previewRanges = parsedFunctions.map { it.functionOffset until it.functionEndOffset }
        val mainRegex = Regex("""\bfn\s+main\s*\(""")
        return mainRegex.replace(this) { match ->
            val insidePreview = previewRanges.any { range -> match.range.first in range }
            if (insidePreview) {
                match.value
            } else {
                match.value.replace("main", "__dioxus_buddy_original_main")
            }
        }
    }

    private fun replaceDirectory(path: Path) {
        if (!path.exists()) {
            path.createDirectories()
            return
        }
        Files.walk(path)
            .sorted(Comparator.reverseOrder())
            .forEach(Files::delete)
        path.createDirectories()
    }

    private fun writeUtf8(
        path: Path,
        text: String,
    ) {
        Files.write(path, text.toByteArray(Charsets.UTF_8))
    }

    private fun String.toSlug(): String {
        return lowercase()
            .replace(Regex("""[^a-z0-9_-]+"""), "-")
            .trim('-')
            .ifBlank { "preview" }
    }
}

internal object DioxusBuddyGeneratedFiles {
    private const val GITIGNORE_TEXT = "# Generated by Dioxus Buddy.\n*\n"

    fun writeGitignore(generatedRootPath: Path) {
        generatedRootPath.createDirectories()
        Files.write(
            generatedRootPath.resolve(".gitignore"),
            GITIGNORE_TEXT.toByteArray(Charsets.UTF_8),
        )
    }
}

internal object CargoPackageMetadata {
    fun resolveEdition(
        manifestText: String,
        manifestRootPath: Path,
        fallback: String,
    ): String {
        return parseTomlStringValue(tableBody(manifestText, "package"), "edition")
            ?: if (hasWorkspaceValue(tableBody(manifestText, "package"), "edition")) {
                val workspace = CargoWorkspaceResolver.resolve(manifestText, manifestRootPath)
                parseTomlStringValue(tableBody(workspace?.text.orEmpty(), "workspace.package"), "edition")
            } else {
                null
            }
            ?: fallback
    }
}

internal object CargoDependencySectionExtractor {
    private val dependencyTableRegex = Regex(
        """^\s*\[(target\.[^\]]+\.dependencies|dependencies(?:\.[^\]]+)?)\]\s*$""",
    )
    private val dependencyNameRegex = Regex("""^\s*([A-Za-z0-9_-]+)\s*(?:\.|=)""")
    private val pathAttributeRegex = Regex("""path\s*=\s*"([^"]+)"""")

    fun extract(
        manifestText: String,
        manifestRootPath: Path,
        sandboxRootPath: Path,
    ): CargoDependencyText {
        val workspace = CargoWorkspaceResolver.resolve(manifestText, manifestRootPath)
        val workspaceDependencies = workspace?.dependencyLinesFor(sandboxRootPath).orEmpty()
        val lines = manifestText.lines()
        val dependencies = mutableListOf<String>()
        val extraTables = mutableListOf<String>()
        var index = 0

        while (index < lines.size) {
            val line = lines[index]
            val tableName = dependencyTableRegex.find(line)?.groupValues?.getOrNull(1)
            if (tableName == null) {
                index++
                continue
            }

            val body = mutableListOf<String>()
            index++
            while (index < lines.size && !lines[index].trimStart().startsWith("[")) {
                body += lines[index]
                index++
            }

            if (tableName == "dependencies") {
                dependencies += body.renderDependencyLines(
                    dependencyRootPath = manifestRootPath,
                    sandboxRootPath = sandboxRootPath,
                    workspaceDependencies = workspaceDependencies,
                    workspaceManifestPath = workspace?.manifestPath,
                )
            } else if (!tableName.endsWith(".dioxus")) {
                val filtered = body.renderDependencyLines(
                    dependencyRootPath = manifestRootPath,
                    sandboxRootPath = sandboxRootPath,
                    workspaceDependencies = workspaceDependencies,
                    workspaceManifestPath = workspace?.manifestPath,
                )
                if (filtered.isNotEmpty()) {
                    extraTables += buildString {
                        appendLine("[$tableName]")
                        filtered.forEach(::appendLine)
                    }.trimEnd()
                }
            }
        }

        return CargoDependencyText(
            dependencies = dependencies.distinct(),
            extraTables = extraTables.distinct(),
        )
    }

    private fun List<String>.renderDependencyLines(
        dependencyRootPath: Path,
        sandboxRootPath: Path,
        workspaceDependencies: Map<String, String>,
        workspaceManifestPath: Path?,
    ): List<String> {
        return mapNotNull { line ->
            val trimmed = line.trim()
            when {
                trimmed.isBlank() -> null
                trimmed.startsWith("#") -> null
                line.dependencyName() == "dioxus" -> null
                trimmed.contains("workspace = true") || Regex("""^\s*[A-Za-z0-9_-]+\.workspace\s*=\s*true\s*$""").matches(trimmed) -> {
                    val dependencyName = line.dependencyName()
                        ?: error("Unable to parse Cargo dependency line: $line")
                    workspaceDependencies[dependencyName]
                        ?: error(
                            "Cargo workspace dependency '$dependencyName' is not declared in " +
                                (workspaceManifestPath?.toString() ?: "the nearest workspace Cargo.toml"),
                        )
                }

                else -> line.rewritePathAttributes(
                    dependencyRootPath = dependencyRootPath,
                    sandboxRootPath = sandboxRootPath,
                )
            }
        }
    }

    private fun CargoWorkspaceManifest.dependencyLinesFor(sandboxRootPath: Path): Map<String, String> {
        val dependenciesText = tableBody(text, "workspace.dependencies") ?: return emptyMap()
        return dependenciesText.lines()
            .mapNotNull { line ->
                val name = line.dependencyName() ?: return@mapNotNull null
                val trimmed = line.trim()
                if (trimmed.isBlank() || trimmed.startsWith("#")) {
                    return@mapNotNull null
                }
                name to line.rewritePathAttributes(
                    dependencyRootPath = rootPath,
                    sandboxRootPath = sandboxRootPath,
                )
            }
            .toMap()
    }

    private fun String.dependencyName(): String? {
        return dependencyNameRegex.find(this)?.groupValues?.getOrNull(1)
    }

    private fun String.rewritePathAttributes(
        dependencyRootPath: Path,
        sandboxRootPath: Path,
    ): String {
        return pathAttributeRegex.replace(this) { match ->
            val rawPath = match.groupValues[1]
            val absoluteDependencyPath = Paths.get(rawPath).let { path ->
                if (path.isAbsolute) {
                    path.normalize()
                } else {
                    dependencyRootPath.resolve(rawPath).normalize()
                }
            }
            val rebasedPath = runCatching {
                sandboxRootPath
                    .toAbsolutePath()
                    .normalize()
                    .relativize(absoluteDependencyPath.toAbsolutePath().normalize())
                    .toString()
                    .replace('\\', '/')
            }.getOrElse {
                absoluteDependencyPath.toString().replace('\\', '/')
            }
            """path = "$rebasedPath""""
        }
    }
}

private object CargoWorkspaceResolver {
    fun resolve(
        manifestText: String,
        manifestRootPath: Path,
    ): CargoWorkspaceManifest? {
        parseTomlStringValue(tableBody(manifestText, "package"), "workspace")
            ?.let { explicitWorkspacePath ->
                val workspaceRootPath = manifestRootPath.resolve(explicitWorkspacePath).normalize()
                return readWorkspaceManifest(workspaceRootPath)
            }

        var directory: Path? = manifestRootPath
        while (directory != null) {
            val candidateManifestPath = directory.resolve("Cargo.toml")
            val candidateText = if (directory == manifestRootPath) {
                manifestText
            } else {
                readManifest(candidateManifestPath)
            }
            if (candidateText != null && tableBody(candidateText, "workspace") != null) {
                return CargoWorkspaceManifest(
                    rootPath = directory,
                    manifestPath = candidateManifestPath,
                    text = candidateText,
                )
            }
            directory = directory.parent
        }
        return null
    }

    private fun readWorkspaceManifest(workspaceRootPath: Path): CargoWorkspaceManifest? {
        val manifestPath = workspaceRootPath.resolve("Cargo.toml")
        val text = readManifest(manifestPath) ?: return null
        return CargoWorkspaceManifest(
            rootPath = workspaceRootPath,
            manifestPath = manifestPath,
            text = text,
        )
    }

    private fun readManifest(path: Path): String? {
        return runCatching {
            if (path.exists()) {
                String(Files.readAllBytes(path), Charsets.UTF_8)
            } else {
                null
            }
        }.getOrNull()
    }
}

private data class CargoWorkspaceManifest(
    val rootPath: Path,
    val manifestPath: Path,
    val text: String,
)

internal data class CargoDependencyText(
    val dependencies: List<String>,
    val extraTables: List<String>,
)

private fun tableBody(
    manifestText: String,
    tableName: String,
): String? {
    val table = Regex("""(?m)^\s*\[${Regex.escape(tableName)}]\s*$""")
        .find(manifestText)
        ?: return null
    val nextTable = Regex("""(?m)^\s*\[""")
        .find(manifestText, table.range.last + 1)
    return manifestText.substring(
        table.range.last + 1,
        nextTable?.range?.first ?: manifestText.length,
    )
}

private fun parseTomlStringValue(
    tableText: String?,
    key: String,
): String? {
    return tableText
        ?.let { Regex("""(?m)^\s*${Regex.escape(key)}\s*=\s*"([^"]+)"""").find(it) }
        ?.groupValues
        ?.getOrNull(1)
}

private fun hasWorkspaceValue(
    tableText: String?,
    key: String,
): Boolean {
    return tableText
        ?.let { Regex("""(?m)^\s*${Regex.escape(key)}\.workspace\s*=\s*true\s*$""").containsMatchIn(it) }
        ?: false
}
