package site.addzero.composebuddy.previewsandbox

import com.intellij.openapi.project.Project
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import kotlin.io.path.createDirectories
import kotlin.io.path.exists

object ComposePreviewSandboxWriter {
    private const val KOTLIN_VERSION = "2.3.20"
    private const val COMPOSE_VERSION = "1.12.0-alpha01"
    private const val COMPOSE_MATERIAL3_VERSION = "1.10.0-alpha05"
    private const val COMPOSE_MATERIAL_ICONS_VERSION = "1.7.3"
    private const val KOTLINX_COROUTINES_VERSION = "1.11.0"

    fun write(
        project: Project,
        snapshot: PreviewSandboxSnapshot,
    ): PreviewSandboxWriteResult? {
        val basePath = project.basePath ?: return null
        val rootDirectory = Paths.get(basePath)
            .resolve(".kmp-buddy")
            .resolve("preview-sandbox")
            .resolve(snapshot.sandboxId)

        replaceDirectory(rootDirectory)

        val names = PreviewSandboxGeneratedNames.from(snapshot)
        val sourceRoot = rootDirectory.resolve("src").resolve("jvmMain").resolve("kotlin")
        val outputFiles = snapshot.files.associateWith { sourceFile ->
            val packageDirectory = sourceFile.packageName
                .takeIf(String::isNotBlank)
                ?.split('.')
                ?.fold(sourceRoot) { current, segment -> current.resolve(segment) }
                ?: sourceRoot
            packageDirectory.createDirectories()
            val outputFile = packageDirectory.resolve(sourceFile.outputFileName)
            Files.write(outputFile, sourceFile.render(snapshot, names).toByteArray(Charsets.UTF_8))
            outputFile
        }

        val settingsFile = writeSettings(rootDirectory, snapshot)
        val buildFile = writeBuildFile(rootDirectory, snapshot, names)
        val gradlePropertiesFile = writeGradleProperties(rootDirectory, snapshot)
        val runnerFile = writeRunner(rootDirectory, snapshot, names)
        writeManifest(
            rootDirectory,
            snapshot,
            names,
            outputFiles.values.toList(),
            listOf(settingsFile, buildFile, gradlePropertiesFile, runnerFile),
        )

        val entryFile = outputFiles.entries
            .firstOrNull { (sourceFile, _) -> sourceFile.key == snapshot.entryFileKey }
            ?.value ?: outputFiles.values.firstOrNull() ?: return null
        val generatedFiles = outputFiles.map { (sourceFile, path) ->
            PreviewSandboxGeneratedFile(
                sourceFileKey = sourceFile.key,
                path = path,
            )
        }

        return PreviewSandboxWriteResult(
            rootDirectory = rootDirectory,
            entryFile = entryFile,
            buildFile = buildFile,
            gradlePropertiesFile = gradlePropertiesFile,
            runnerFile = runnerFile,
            classpathFile = rootDirectory.resolve("build").resolve("kmpBuddyPreview").resolve("classpath.txt"),
            runnerMainClass = names.runnerMainClass,
            entryComposableName = names.entryComposableName,
            generatedFiles = generatedFiles,
            generatedFileCount = generatedFiles.size,
            declarationCount = snapshot.declarationCount,
        )
    }

    private fun PreviewSandboxSourceFile.render(
        snapshot: PreviewSandboxSnapshot,
        names: PreviewSandboxGeneratedNames,
    ): String {
        return buildString {
            appendLine("// Generated by KMP Buddy Preview Sandbox.")
            appendLine("// Original file: $originalPath")
            appendLine()
            if (packageName.isNotBlank()) {
                appendLine("package $packageName")
                appendLine()
            }
            imports.forEach { importText ->
                appendLine(importText)
            }
            if (imports.isNotEmpty()) {
                appendLine()
            }
            declarations.forEachIndexed { index, declaration ->
                if (index > 0) {
                    appendLine()
                }
                appendLine(declaration)
            }
            if (key == snapshot.entryFileKey) {
                appendLine()
                appendLine("@androidx.compose.runtime.Composable")
                appendLine("internal fun ${names.entryComposableName}() {")
                appendLine("    ${snapshot.previewName.renderKotlinCallName()}()")
                appendLine("}")
            }
        }
    }

    private fun writeSettings(
        rootDirectory: Path,
        snapshot: PreviewSandboxSnapshot,
    ): Path {
        val settingsFile = rootDirectory.resolve("settings.gradle.kts")
        val projectName = "kmp-buddy-preview-${snapshot.sandboxId}".replace('"', '-')
        val text = buildString {
            appendLine("pluginManagement {")
            appendLine("    repositories {")
            appendLine("        google()")
            appendLine("        mavenCentral()")
            appendLine("        gradlePluginPortal()")
            appendLine("        maven(\"https://maven.pkg.jetbrains.space/public/p/compose/dev\")")
            appendLine("    }")
            appendLine("}")
            appendLine()
            appendLine("dependencyResolutionManagement {")
            appendLine("    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)")
            appendLine("    repositories {")
            appendLine("        google()")
            appendLine("        mavenCentral()")
            appendLine("        maven(\"https://maven.pkg.jetbrains.space/public/p/compose/dev\")")
            appendLine("    }")
            appendLine("}")
            appendLine()
            appendLine("rootProject.name = \"${projectName.escapeKotlinString()}\"")
        }
        Files.write(settingsFile, text.toByteArray(Charsets.UTF_8))
        return settingsFile
    }

    private fun writeBuildFile(
        rootDirectory: Path,
        snapshot: PreviewSandboxSnapshot,
        names: PreviewSandboxGeneratedNames,
    ): Path {
        val buildFile = rootDirectory.resolve("build.gradle.kts")
        val text = buildString {
            appendLine("import java.io.File")
            appendLine("import org.gradle.jvm.tasks.Jar")
            appendLine("import org.jetbrains.kotlin.gradle.dsl.JvmTarget")
            appendLine()
            appendLine("plugins {")
            appendLine("    kotlin(\"multiplatform\") version \"$KOTLIN_VERSION\"")
            appendLine("    id(\"org.jetbrains.compose\") version \"$COMPOSE_VERSION\"")
            appendLine("    id(\"org.jetbrains.kotlin.plugin.compose\") version \"$KOTLIN_VERSION\"")
            if (snapshot.usesKotlinSerialization()) {
                appendLine("    id(\"org.jetbrains.kotlin.plugin.serialization\") version \"$KOTLIN_VERSION\"")
            }
            appendLine("}")
            appendLine()
            appendLine("val kmpBuddyPreviewDependencyClasspath = files(")
            snapshot.dependencyClassPath.forEach { dependencyPath ->
                appendLine("    \"${dependencyPath.escapeKotlinString()}\",")
            }
            appendLine(")")
            appendLine()
            appendLine("kotlin {")
            appendLine("    jvm {")
            appendLine("        compilerOptions {")
            appendLine("            jvmTarget.set(JvmTarget.fromTarget(\"${snapshot.jvmTarget.escapeKotlinString()}\"))")
            appendLine("        }")
            appendLine("    }")
            appendLine()
            appendLine("    sourceSets {")
            appendLine("        commonMain.dependencies {")
            appendLine("            implementation(\"org.jetbrains.compose.runtime:runtime:$COMPOSE_VERSION\")")
            appendLine("            implementation(\"org.jetbrains.compose.foundation:foundation:$COMPOSE_VERSION\")")
            appendLine("            implementation(\"org.jetbrains.compose.ui:ui:$COMPOSE_VERSION\")")
            appendLine("            implementation(\"org.jetbrains.compose.ui:ui-tooling-preview:$COMPOSE_VERSION\")")
            appendLine("            implementation(\"org.jetbrains.compose.material:material:$COMPOSE_VERSION\")")
            appendLine("            implementation(\"org.jetbrains.compose.material:material-icons-extended:$COMPOSE_MATERIAL_ICONS_VERSION\")")
            appendLine("            implementation(\"org.jetbrains.compose.material3:material3:$COMPOSE_MATERIAL3_VERSION\")")
            appendLine("            implementation(\"org.jetbrains.compose.components:components-resources:$COMPOSE_VERSION\")")
            appendLine("        }")
            appendLine("        jvmMain.dependencies {")
            appendLine("            implementation(kmpBuddyPreviewDependencyClasspath)")
            appendLine("            implementation(compose.desktop.currentOs)")
            appendLine("            implementation(\"org.jetbrains.kotlinx:kotlinx-coroutines-swing:$KOTLINX_COROUTINES_VERSION\")")
            snapshot.externalMavenDependencies.forEach { dependency ->
                appendLine("            implementation(\"${dependency.escapeKotlinString()}\")")
            }
            appendLine("        }")
            appendLine("    }")
            appendLine("}")
            appendLine()
            appendLine("compose.desktop {")
            appendLine("    application {")
            appendLine("        mainClass = \"${names.runnerMainClass}\"")
            appendLine("        jvmArgs += listOf(\"-Dsun.java2d.metal=false\")")
            appendLine("    }")
            appendLine("}")
            appendLine()
            appendLine("tasks.register(\"writeKmpBuddyPreviewClasspath\") {")
            appendLine("    dependsOn(\"jvmJar\")")
            appendLine("    val outputFile = layout.buildDirectory.file(\"kmpBuddyPreview/classpath.txt\")")
            appendLine("    outputs.file(outputFile)")
            appendLine("    doLast {")
            appendLine("        val runtimeClasspath = configurations.getByName(\"jvmRuntimeClasspath\").files")
            appendLine("        val jarFile = tasks.named<Jar>(\"jvmJar\").get().archiveFile.get().asFile")
            appendLine("        val classpath = (runtimeClasspath + jarFile).joinToString(File.pathSeparator) { it.absolutePath }")
            appendLine("        outputFile.get().asFile.apply {")
            appendLine("            parentFile.mkdirs()")
            appendLine("            writeText(classpath)")
            appendLine("        }")
            appendLine("    }")
            appendLine("}")
        }
        Files.write(buildFile, text.toByteArray(Charsets.UTF_8))
        return buildFile
    }

    private fun writeGradleProperties(
        rootDirectory: Path,
        snapshot: PreviewSandboxSnapshot,
    ): Path {
        val gradlePropertiesFile = rootDirectory.resolve("gradle.properties")
        Files.write(
            gradlePropertiesFile,
            PreviewSandboxGradleJvm.gradlePropertiesText(snapshot.gradleJavaHome).toByteArray(Charsets.UTF_8),
        )
        return gradlePropertiesFile
    }

    private fun PreviewSandboxSnapshot.usesKotlinSerialization(): Boolean {
        return PreviewSandboxExternalDependencies.KOTLINX_SERIALIZATION_CORE in externalMavenDependencies
    }

    private fun writeRunner(
        rootDirectory: Path,
        snapshot: PreviewSandboxSnapshot,
        names: PreviewSandboxGeneratedNames,
    ): Path {
        val sourceRoot = rootDirectory.resolve("src").resolve("jvmMain").resolve("kotlin")
        val packageDirectory = snapshot.previewPackage
            .takeIf(String::isNotBlank)
            ?.split('.')
            ?.fold(sourceRoot) { current, segment -> current.resolve(segment) }
            ?: sourceRoot
        packageDirectory.createDirectories()

        val runnerFile = packageDirectory.resolve("PreviewSandboxRunner.kt")
        val text = buildString {
            appendLine("// Generated by KMP Buddy Preview Sandbox.")
            appendLine()
            if (snapshot.previewPackage.isNotBlank()) {
                appendLine("package ${snapshot.previewPackage}")
                appendLine()
            }
            appendLine("import androidx.compose.foundation.layout.Box")
            appendLine("import androidx.compose.foundation.layout.fillMaxSize")
            appendLine("import androidx.compose.foundation.layout.padding")
            appendLine("import androidx.compose.material3.MaterialTheme")
            appendLine("import androidx.compose.material3.Surface")
            appendLine("import androidx.compose.ui.Modifier")
            appendLine("import androidx.compose.ui.awt.ComposePanel")
            appendLine("import androidx.compose.ui.unit.dp")
            appendLine("import androidx.compose.ui.window.Window")
            appendLine("import androidx.compose.ui.window.application")
            appendLine("import javax.swing.JComponent")
            appendLine()
            appendLine("fun main() = application {")
            appendLine("    Window(")
            appendLine("        onCloseRequest = ::exitApplication,")
            appendLine("        title = \"KMP Buddy Preview - ${snapshot.previewDisplayName.escapeKotlinString()}\",")
            appendLine("    ) {")
            appendLine("        MaterialTheme {")
            appendLine("            Surface(modifier = Modifier.fillMaxSize()) {")
            appendLine("                Box(modifier = Modifier.fillMaxSize().padding(16.dp)) {")
            appendLine("                    ${names.entryComposableName}()")
            appendLine("                }")
            appendLine("            }")
            appendLine("        }")
            appendLine("    }")
            appendLine("}")
            appendLine()
            appendLine("fun createKmpBuddyPreviewPanel(): JComponent {")
            appendLine("    return ComposePanel().apply {")
            appendLine("        setContent {")
            appendLine("            KmpBuddyPreviewContent()")
            appendLine("        }")
            appendLine("    }")
            appendLine("}")
            appendLine()
            appendLine("@androidx.compose.runtime.Composable")
            appendLine("private fun KmpBuddyPreviewContent() {")
            appendLine("    MaterialTheme {")
            appendLine("        Surface(modifier = Modifier.fillMaxSize()) {")
            appendLine("            Box(modifier = Modifier.fillMaxSize().padding(16.dp)) {")
            appendLine("                ${names.entryComposableName}()")
            appendLine("            }")
            appendLine("        }")
            appendLine("    }")
            appendLine("}")
        }
        Files.write(runnerFile, text.toByteArray(Charsets.UTF_8))
        return runnerFile
    }

    private fun writeManifest(
        rootDirectory: Path,
        snapshot: PreviewSandboxSnapshot,
        names: PreviewSandboxGeneratedNames,
        outputFiles: List<Path>,
        runnerFiles: List<Path>,
    ) {
        val manifest = buildString {
            appendLine("KMP Buddy preview sandbox")
            appendLine()
            appendLine("Sandbox: ${snapshot.sandboxId}")
            appendLine("Declarations: ${snapshot.declarationCount}")
            appendLine("Entry composable: ${names.entryComposableName}")
            appendLine("Main class: ${names.runnerMainClass}")
            appendLine()
            appendLine("Reachable AST files:")
            outputFiles.forEach { file ->
                appendLine("- ${rootDirectory.relativize(file)}")
            }
            appendLine()
            appendLine("Runner files:")
            runnerFiles.forEach { file ->
                appendLine("- ${rootDirectory.relativize(file)}")
            }
            appendLine()
            appendLine("Run the Gradle run task or the IDE Gradle run configuration to open the graphical preview window.")
            appendLine("Run the writeKmpBuddyPreviewClasspath task to render the preview inside the IDE panel.")
            appendLine("This directory is generated and can be deleted safely.")
        }
        Files.write(rootDirectory.resolve("README.txt"), manifest.toByteArray(Charsets.UTF_8))
    }

    private fun replaceDirectory(path: Path) {
        if (path.exists()) {
            Files.walk(path)
                .sorted(Comparator.reverseOrder())
                .forEach(Files::deleteIfExists)
        }
        path.createDirectories()
    }

    private fun String.renderKotlinCallName(): String {
        return if (matches(Regex("""[A-Za-z_][A-Za-z0-9_]*"""))) {
            this
        } else {
            "`" + replace("`", "") + "`"
        }
    }

    private fun String.escapeKotlinString(): String {
        return buildString {
            this@escapeKotlinString.forEach { char ->
                when (char) {
                    '\\' -> append("\\\\")
                    '"' -> append("\\\"")
                    '\n' -> append("\\n")
                    '\r' -> append("\\r")
                    '\t' -> append("\\t")
                    else -> append(char)
                }
            }
        }
    }
}

private data class PreviewSandboxGeneratedNames(
    val entryComposableName: String,
    val runnerMainClass: String,
) {
    companion object {
        fun from(snapshot: PreviewSandboxSnapshot): PreviewSandboxGeneratedNames {
            val suffix = snapshot.sandboxId
                .takeLast(12)
                .toKotlinIdentifier()
            val packagePrefix = snapshot.previewPackage
                .takeIf(String::isNotBlank)
                ?.let { packageName -> "$packageName." }
                .orEmpty()
            return PreviewSandboxGeneratedNames(
                entryComposableName = "KmpBuddyPreviewEntry_$suffix",
                runnerMainClass = "${packagePrefix}PreviewSandboxRunnerKt",
            )
        }

        private fun String.toKotlinIdentifier(): String {
            val cleaned = mapIndexed { index, char ->
                val valid = if (index == 0) {
                    char == '_' || char.isLetter()
                } else {
                    char == '_' || char.isLetterOrDigit()
                }
                if (valid) char else '_'
            }.joinToString("")
            return cleaned.trim('_').ifBlank { "Preview" }
        }
    }
}
