package site.addzero.composebuddy.previewsandbox

import java.nio.file.Paths

object PreviewSandboxGradleJvm {
    const val GRADLE_JAVA_HOME_PROPERTY: String = "org.gradle.java.home"
    const val JAVA_HOME_ENV: String = "JAVA_HOME"

    fun currentJavaHome(): String {
        val javaHome = System.getProperty("java.home").orEmpty().trim()
        if (javaHome.isBlank()) {
            return ""
        }
        return runCatching { Paths.get(javaHome).toAbsolutePath().normalize().toString() }
            .getOrDefault(javaHome)
    }

    fun gradleSystemPropertyArgument(javaHome: String): String {
        return "-D$GRADLE_JAVA_HOME_PROPERTY=$javaHome"
    }

    fun gradleVmOption(javaHome: String): String {
        return "-D$GRADLE_JAVA_HOME_PROPERTY=${javaHome.quoteCommandLineValueIfNeeded()}"
    }

    fun gradleScriptParameter(javaHome: String): String {
        return gradleVmOption(javaHome)
    }

    fun gradlePropertiesText(javaHome: String): String {
        return buildString {
            appendLine("# Generated by KMP Buddy Preview Sandbox.")
            if (javaHome.isNotBlank()) {
                appendLine("$GRADLE_JAVA_HOME_PROPERTY=${javaHome.escapeGradlePropertyValue()}")
            }
        }
    }

    private fun String.quoteCommandLineValueIfNeeded(): String {
        if (none(Char::isWhitespace) && none { char -> char == '"' }) {
            return this
        }
        return "\"" + replace("\\", "\\\\").replace("\"", "\\\"") + "\""
    }

    private fun String.escapeGradlePropertyValue(): String {
        return buildString {
            this@escapeGradlePropertyValue.forEach { char ->
                when (char) {
                    '\\' -> append("\\\\")
                    '\n' -> append("\\n")
                    '\r' -> append("\\r")
                    '\t' -> append("\\t")
                    else -> append(char)
                }
            }
        }
    }
}
