package site.addzero.composebuddy.deadcode

import com.intellij.openapi.project.Project
import com.intellij.openapi.vfs.LocalFileSystem
import com.intellij.openapi.vfs.VfsUtil
import com.intellij.openapi.vfs.VirtualFile
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption
import java.time.Instant
import kotlin.io.path.createDirectories
import kotlin.io.path.exists

class DeadCodeMirrorWriter(
    private val project: Project,
) {
    fun write(
        sourceModuleRoot: VirtualFile,
        analysis: DeadCodeAnalysisResult,
    ): DeadCodeCullResult? {
        val projectRoot = DeadCodePaths.projectRoot(project) ?: return null
        val mirrorRoot = DeadCodePaths.mirrorModuleRoot(project, sourceModuleRoot) ?: return null
        return writeToMirror(
            projectRoot = projectRoot,
            mirrorRoot = mirrorRoot,
            analysis = analysis,
        )
    }

    fun writeToMirror(
        projectRoot: Path,
        mirrorRoot: Path,
        analysis: DeadCodeAnalysisResult,
    ): DeadCodeCullResult {
        val deadFiles = analysis.movableDeadFiles

        mirrorRoot.createDirectories()
        ensureTrackedDeadCodeGitignore(projectRoot)
        copyBuildFile(analysis.sourceModulePath, mirrorRoot)

        val movedFiles = deadFiles.mapNotNull { file ->
            val sourcePath = file.sourcePath
            if (!sourcePath.exists()) {
                return@mapNotNull null
            }
            val mirrorPath = mirrorRoot.resolve(file.relativePath)
            mirrorPath.parent.createDirectories()
            val sha256 = DeadCodeFileHash.sha256(sourcePath)
            Files.move(sourcePath, mirrorPath, StandardCopyOption.REPLACE_EXISTING)
            deleteEmptyParents(sourcePath.parent, analysis.sourceModulePath)
            DeadCodeMovedFile(
                relativePath = file.relativePath,
                sourcePath = sourcePath.toString(),
                mirrorPath = mirrorPath.toString(),
                sha256 = sha256,
            )
        }

        val mixedFiles = analysis.mixedFiles.map { file ->
            DeadCodeMixedFile(
                relativePath = file.relativePath,
                sourcePath = file.sourcePath.toString(),
                liveDeclarations = file.liveDeclarations.map { declaration -> declaration.displayName() },
                deadDeclarations = file.deadDeclarations.map { declaration -> declaration.displayName() },
            )
        }

        val manifest = DeadCodeManifest(
            analyzerVersion = DeadCodeConstants.ANALYZER_VERSION,
            createdAt = Instant.now().toString(),
            sourceModulePath = analysis.sourceModulePath.toString(),
            mirrorRootPath = mirrorRoot.toString(),
            sourceBuildFilePath = analysis.sourceModulePath.resolve("build.gradle.kts").toString(),
            mirrorBuildFilePath = mirrorRoot.resolve("build.gradle.kts").toString(),
            movedFiles = movedFiles,
            mixedFiles = mixedFiles,
            reachableDeclarationCount = analysis.reachableDeclarationCount,
        )
        val manifestPath = mirrorRoot.resolve(DeadCodeConstants.MANIFEST_FILE_NAME)
        DeadCodeManifestJson.write(manifestPath, manifest)

        val reportPath = mirrorRoot.resolve(DeadCodeConstants.REPORT_FILE_NAME)
        Files.write(reportPath, renderReport(manifest).toByteArray(Charsets.UTF_8))

        refresh(projectRoot, mirrorRoot, analysis.sourceModulePath)
        return DeadCodeCullResult(
            mirrorRoot = mirrorRoot,
            manifestPath = manifestPath,
            reportPath = reportPath,
            movedFileCount = movedFiles.size,
            mixedFileCount = mixedFiles.size,
        )
    }

    private fun copyBuildFile(sourceModulePath: Path, mirrorRoot: Path) {
        val sourceBuildFile = sourceModulePath.resolve("build.gradle.kts")
        if (!sourceBuildFile.exists()) {
            return
        }
        val mirrorBuildFile = mirrorRoot.resolve("build.gradle.kts")
        val sourceText = String(Files.readAllBytes(sourceBuildFile), Charsets.UTF_8)
        val text = buildString {
            appendLine("// Generated by KMP Buddy Dead Code Culling.")
            appendLine("// This mirror build file is intentionally not included by the source project.")
            append(sourceText)
            if (!sourceText.endsWith("\n")) {
                appendLine()
            }
        }
        Files.write(mirrorBuildFile, text.toByteArray(Charsets.UTF_8))
    }

    private fun ensureTrackedDeadCodeGitignore(projectRoot: Path) {
        val gitignore = projectRoot.resolve(".gitignore")
        val existing = if (gitignore.exists()) {
            String(Files.readAllBytes(gitignore), Charsets.UTF_8)
        } else {
            ""
        }
        val linesToAdd = listOf(
            "",
            "# KMP Buddy dead-code mirror modules are intentionally versionable.",
            "!.kmp-buddy/",
            "!.kmp-buddy/dead-code-modules/",
            "!.kmp-buddy/dead-code-modules/**",
        )
        if (linesToAdd.drop(2).all(existing::contains)) {
            return
        }
        Files.write(
            gitignore,
            buildString {
                append(existing.trimEnd())
                appendLine()
                linesToAdd.forEach(::appendLine)
            }.toByteArray(Charsets.UTF_8),
        )
    }

    private fun renderReport(manifest: DeadCodeManifest): String {
        return buildString {
            appendLine("# KMP Buddy Dead Code Report")
            appendLine()
            appendLine("- Analyzer version: ${manifest.analyzerVersion}")
            appendLine("- Created at: ${manifest.createdAt}")
            appendLine("- Source module: ${manifest.sourceModulePath}")
            appendLine("- Mirror module: ${manifest.mirrorRootPath}")
            appendLine("- Reachable declarations: ${manifest.reachableDeclarationCount}")
            appendLine("- Moved whole-file dead code: ${manifest.movedFiles.size}")
            appendLine("- Mixed files left in place: ${manifest.mixedFiles.size}")
            appendLine()
            appendLine("## Moved Files")
            appendLine()
            if (manifest.movedFiles.isEmpty()) {
                appendLine("No whole-file dead code was moved.")
            } else {
                manifest.movedFiles.forEach { file ->
                    appendLine("- `${file.relativePath}`")
                }
            }
            appendLine()
            appendLine("## Mixed Files")
            appendLine()
            if (manifest.mixedFiles.isEmpty()) {
                appendLine("No mixed files were detected.")
            } else {
                manifest.mixedFiles.forEach { file ->
                    appendLine("### `${file.relativePath}`")
                    appendLine()
                    appendLine("Live declarations: ${file.liveDeclarations.joinToString().ifBlank { "none" }}")
                    appendLine()
                    appendLine("Dead declarations left in place: ${file.deadDeclarations.joinToString().ifBlank { "none" }}")
                    appendLine()
                }
            }
        }
    }

    private fun DeadCodeDeclarationKey.displayName(): String {
        return "$name@$offset"
    }

    private fun deleteEmptyParents(
        start: Path,
        stop: Path,
    ) {
        var current: Path? = start
        while (current != null && current != stop && current.startsWith(stop)) {
            val children = Files.list(current).use { stream -> stream.findAny().isPresent }
            if (children) {
                return
            }
            Files.deleteIfExists(current)
            current = current.parent
        }
    }

    private fun refresh(vararg paths: Path) {
        val files = paths.mapNotNull { path ->
            LocalFileSystem.getInstance().refreshAndFindFileByNioFile(path)
        }.toTypedArray()
        if (files.isNotEmpty()) {
            VfsUtil.markDirtyAndRefresh(false, true, true, *files)
        }
    }
}
